sudo: false
language: node_js
node_js:
- '6'
script:
- npm run build -- --release
- npm run release
- echo $TOKEN >> token
- npm run upload
branches:
  only:
  - dev
env:
  global:
    secure: ZkfJh9X99oxfniXxhGiwGKRJGYW5F9elL06bxBNe6Kh8/4nEYGt8rAnlXwf8h9/uXzTZemWo8FLZZ3BwW8MLbWclSBQ2j9nU3g+JMJY+nGHNb6OoA1JzjLgI/QMUdVl2o2+0EbcePSoqHqXMHH8wp2GmVaAHyMZ3716eS/834IaoFVEa+YH/COJbRYxblW20k987V28yJH909ByImwzOzeNV7lZEkTYltjuYfwHWzhbdoGUJ6hbu0xqo6+u4jyupJTRGLXPg9eeCpQqbFjdkFGVqqq0QzOd1bt0t8Ze627qr+83lcGIgBqpNZbUoR7nd8GCH/rIMhD2PXrsjDV+/R0aubkevVXRxM+WYrIPDHJw62a5RAPKhVg0JNUEiYj9Gttf1JjlnADG5AVTTX9zio+BPFnYNtsZ9b5bSHtstuE5nse+TGuWFite/C9vE7Cwo0USytRUwXOM9Pk4fo8Om/1HGYfWoI+9QmQRqMswxkq8dRD9bIF/SebutAMSXJbqW6b+3XdLnIuSJMYSq/tFrkIrqppX+VB0y+y++zeDjvSHND/5bAVhG13CkqsD1RyKoYQTw2xWag4nUTM1E0NlLNaaOCMyE8PtWJalhLrtQaqnnkj7sXhcxBYdmen38NBSbKDcoh/wADYpoYb38NYuUi8mIsW1Ma64xx7hh1b3AqWc=
